name: Build and Push Docker image

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push multi-arch Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/weather-application/spring-app
          GIT_SHA=${{ github.sha }}

          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg JAR_FILE=target/*.jar \
            -t $IMAGE_NAME:latest \
            -t $IMAGE_NAME:$GIT_SHA \
            --push .
